---
- name: Analyze the dnf event.payload
  hosts: all
  gather_facts: false

  tasks:
  - debug:
      var: hostvars[inventory_hostname]

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

  - name: Print greeting
    ansible.builtin.debug:
        var: greeting

  - name: Print ansible_eda.event
    ansible.builtin.debug:
        var: ansible_eda.event

  - name: Print ansible_eda.event.body
    ansible.builtin.debug:
        var: ansible_eda.event.body

  - name: Launch a Workflow with extra_vars without waiting
    ansible.controller.workflow_launch:
      workflow_template: "eda_wf"
      extra_vars:
        var1: My First Variable
        var2: My Second Variable
        ansible_eda: "{{ ansible_eda }}"
      wait: False
