- name: Read messages from a kafka topic and act on them
  hosts: localhost 

  sources:   
    - ansible.eda.kafka:
        host: tools.home.glroland.com
        port: 9092
        topic: eda
        offset: earliest

  rules:

    - name: hello world event handler
      condition: event.body contains 'hello'
      action:
        run_job_template:
          name: eda_wf_event
          organization: Default
          job_args: 
            extra_vars: 
              greeting: "WORLD!"

    - name: default event handler
      condition: event.body != ''
      action:
        run_job_template:
          name: eda_event
          organization: Default
          job_args: 
            extra_vars: 
              greeting: "BOOOOOH....."
