---
- name: Analyze the dnf event.payload
  hosts: all
  gather_facts: false

  tasks:
  - debug:
      var: hostvars[inventory_hostname]

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

  - debug:
      msg: "{{ ansible_eda.event.body }}"
