---
- name: Analyze the dnf event.payload
  hosts: kafka.example.com
  gather_facts: false

  tasks:
  - set_fact:
      event_content: "{{ event.payload.replace('\"', '') }}"

  - debug:
      msg: "{{ event_content }}"
