---
- name: Analyze the dnf event.payload
  hosts: all
  gather_facts: false

  tasks:
  - debug:
      var: hostvars[inventory_hostname]
#  - debug:
#      msg: "{{ ansible_eda.event.body }}"

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
