---
- name: Analyze the dnf event.payload
  hosts: all
  gather_facts: false

  tasks:
  - debug:
      var: hostvars[inventory_hostname]

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

  - name: Print FOO
    ansible.builtin.debug:
        var: foo

  - name: Print FOO
    ansible.builtin.debug:
        var: eda_event_body

  - name: Print FOO
    ansible.builtin.debug:
        var: event

  - name: Print FOO
    ansible.builtin.debug:
        var: ansible_eda.event

  - name: Print FOO
    ansible.builtin.debug:
        var: ansible_eda.event.body

